# @package _global_


module:
  _target_: emg2qwerty.lightning.TDSConvCTCModule
  in_features: 528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32  # Total temporal receptive field of 125 samples given 4 layers

  channel_mask:
    _target_: emg2qwerty.modules.ChannelMask
    fixed: true           # fixed mask across all batches and epochs
    drop_prob: 0.675       # drop 50% of channels
    mode: gaussian            # or "gaussian"
    gaussian_std: 1.0     # only used if mode="gaussian"
    per_example: false
    active_in_eval: true

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
